[versions]
kotlin = "1.9.22"
http4k = "5.12.0.0"
forkhandlesVersion = "2.11.1.0"
junit-jupiter = "5.10.1"
result4k = '2.2.0.0'

[libraries]
http4k-core = { module = "org.http4k:http4k-core", version.ref = "http4k" }
http4k-format-jackson = { module = "org.http4k:http4k-format-jackson", version.ref = "http4k" }
http4k-format-xml = { module = "org.http4k:http4k-format-xml", version.ref = "http4k" }
http4k-template-handlebars = { module = "org.http4k:http4k-template-handlebars", version.ref = "http4k" }
http4k-contract = { module = "org.http4k:http4k-contract", version.ref = "http4k" }
http4k-format-argo = { module = "org.http4k:http4k-format-argo", version.ref = "http4k" }
http4k-client-apache = { module = "org.http4k:http4k-client-apache", version.ref = "http4k" }
http4k-server-jetty = { module = "org.http4k:http4k-server-jetty", version.ref = "http4k" }
http4k-client-websocket = { module = "org.http4k:http4k-client-websocket", version.ref = "http4k" }


[bundles]
http4k = ["http4k-core", "http4k-format-jackson", "http4k-format-xml", "http4k-template-handlebars", "http4k-contract", "http4k-format-argo", "http4k-client-apache", "http4k-server-jetty", "http4k-client-websocket"]

#
#[plugins]
#gradleVersions = { id = "com.github.ben-manes.versions", version = "0.50.0" }